all:
	pdflatex manual_pt.tex
	pdflatex manual_pt.tex
	pdflatex manual_en.tex
	pdflatex manual_en.tex
	pdflatex manual_en_sbitx.tex
	pdflatex manual_en_sbitx.tex
	pdflatex manual_es.tex
	pdflatex manual_es.tex
	pdflatex software_pt.tex
	pdflatex software_pt.tex
	pdflatex hardware_en.tex
	pdflatex hardware_en.tex
	pdflatex software_en.tex
	pdflatex software_en.tex
	pdflatex sbitx.tex
	pdflatex sbitx.tex

.PHONY:
clean:
	rm -f software_pt.aux software_pt.out software_pt.log software_pt.toc software_pt.pdf
	rm -f hardware_en.aux hardware_en.out hardware_en.log hardware_en.toc hardware_en.pdf
	rm -f software_en.aux software_en.out software_en.log software_en.toc software_en.pdf
	rm -f manual_pt.aux manual_pt.out manual_pt.log manual_pt.toc manual_pt.pdf
	rm -f manual_en_sbitx.aux manual_en_sbitx.out manual_en_sbitx.log manual_en_sbitx.toc manual_en_sbitx.pdf
	rm -f manual_en.aux manual_en.out manual_en.log manual_en.toc manual_en.pdf
	rm -f manual_es.aux manual_es.out manual_es.log manual_es.toc manual_es.pdf
	rm -f sbitx.aux sbitx.out sbitx.log sbitx.toc sbitx.pdf
